name: Docker Workflow
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.event.repository.name }}
          platforms: linux/amd64,linux/arm64
          registry: ghcr.io
          push: true

